apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: oidc-plugin-config
  namespace: ingress-apisix
spec:
  plugins:
  - name: openid-connect
    enable: true
    config:
      bearer_only: false
      client_id: "myclient"
      client_secret: "LhKelre9pHZRsVZvi17gk483nrPHvIl0"
      discovery: "http://keycloak:8080/realms/myrealm/.well-known/openid-configuration"
      scope: "openid profile"
      redirect_uri: "http://local.httpbin.org/anything/callback"
