apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: ingress-apisix
  labels:
    app: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      name: httpbin
      labels:
        app: httpbin
    spec:
      containers:
        - name: httpbin
          image: mccutchen/go-httpbin
          imagePullPolicy: Always
      restartPolicy: Always
