apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: ingress-apisix
spec:
  selector:
    app: httpbin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
